version: '3.4'

services:
  ngsh5:
    image: chwj2306/ngsh5
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
